### ISSUE TITLE
Option to force replacement of an element/components

### ISSUE THREAD

**Issue by NoCodeMonkey** [devstark-com/vue-layout-broker#1]
Would it be possible to add an optional parameter that can set :key="$route.fullPath" on the router-view so instead of reusing an element or component, it forces replacement?

See https://stackoverflow.com/questions/52847979/what-is-router-view-key-route-fullpath

**Comment by Saymon-biz** [comment]
If you need that in order to trigger transitions, the ability to pass `:key` inside is not only thing you need. The `<router-view>` itself has to be also wrapped with a `<transition>` so I have to add that somehow into the plugin.

The best way is if you'll provide some workaround that fits your need e.g. in a fork of https://codesandbox.io/s/42m1lrj6l7 but using the component from `/src/layouts/LayoutBroker.vue` instead of NPM package (this way you'll be able to modify the code).

Please, reopen this issue if you still need this feature and if you will have some solution. I'll try to add this stuff the proper way
